### PR TITLE
Switch filepack/mset hash algorithm to CRC32 compatible with cksum tool

### PR DESCRIPTION
**Pull request by dukesrg**
rxTools boots fine with that change

### CODE REVIEW

**Comment by Syphurith** [comment]
I wonder if @roxas75 would still accept your pull, since rxTool has already been sent to @AlbertoSONIC after Roxas announced his retirement from this.

**Comment by dukesrg** [comment]
I missed @roxas75 retirement while coding those changes :(
But @AlbertoSONIC recently posted in the gbatemp topic that this branch is the main again. I suppose @roxas75 added @AlbertoSONIC as a collaborator

**Comment by AlbertoSONIC** [comment]
Yeah i'll pull this request ;)

**Comment by AlbertoSONIC** [comment]
*merge this pull request

**Comment by Syphurith** [comment]
Yes, i've seen the collaborator tag of AlbertoSONIC now.

**Pull request merged**
