### PR TITLE
Merge CakeHaX

### PR DESCRIPTION
**Pull request by ApacheThunder**
I've kept this branch maintained and synced with main branch . You can use this to merge CakeHaX into rxTools 3.0. You should get this out of the way now before you do any major changes to makefile unless you want to enlist the help of mid-kid again. :P

You can compare files to see if I missed anything. But I'm sure I got all the latest commits as of this pull request. I compiled and tested this. It runs fine from MSET 9.x and spider on my 9.2 o3DS (USA console)

The only personal changes I've done to this branch is disable encryption of filepack/data.bin (it's not needed anymore since most of rxTools in CakeHaX is unencrypted) I've also given rxInstaller a new top screen logo. Do what you want with that. Just something to replace the old one for now. :P

rxInstaller hasn't been updated to use correct MSET rop yet. But my fork of CakeROP works just fine. You can use that until rxInstaller is fixed. I've remmed out instances of rxInstaller from main makefile. Mid-Kid didn't do that correctly as it won't compile rxInstaller when using "make release". I'll let someone else sort that out once rxInstaller is updated with new ROP for CakeHaX. (and yes the makefile does include the latest commits. I was careful to integrate changes you've made to makefile up to this point)

For what ever reason this can't be auto merged. Most likely due to the submodules. You can include CakeHaX and it's submodule (p3ds) as normal folders. (that and maybe the pull request isn't quite correct. You can download this branch with github desktop app and merge things manually. It's probably going to be the best way of doing this if GitHub gives you trouble)

Note you'll need to swap the addresses of bot_screen and bot_screen2 for bottom screen to work correctly on MSET/Spider. Ninjhax still broken for this branch until you get screen addresses fixed. ;)
(I have not touched draw.h code in this branch. Currently the same as what you currently have)

### CODE REVIEW

**Comment by AlbertoSONIC** [comment]
Is this updated with latest rxtools master changes?

**Comment by ApacheThunder** [comment]
Yes it is. You can double check. I'm pretty darn sure it's got all the commits. I have been keeping track of it for the last few days. :D

**Comment by AlbertoSONIC** [comment]
I need ninjhax support to finish the GUI. Can you keep your repo updated and i'll merge it only when GUI work is done? Once we'll have your repo merged with rxtools master, we'll add Ninjhax support again ;)

**Comment by ApacheThunder** [comment]
Sure. The bottom screen stuff still freezes in Ninjhax. (though I did fix brahma stuff to load CakeHax payload and It works with my main branch which is rxTools 2.6 but with CakeHax added. Ninjhax on that branch works if I remmed out all the bottom screen stuff I added)

So I'm guessing it's just the bottom screen stuff not getting along with Ninjhax. I will keep the branch uptodate. But be careful with what you do to makefile. I already noticed one pull request (pull request #64 to be specific) that I would have a difficult time integrating into my CakeHaX build. Maybe that's something you can do after you get GUI done and CakeHax merged. :D

**Comment by dukesrg** [comment]
So mset hax sources is not needed there?

**Comment by AlbertoSONIC** [comment]
Yeah i'll look into it :)

**Comment by ApacheThunder** [comment]
No not really. I forked CakeROP:

https://github.com/ApacheThunder/rxToolsCakeROP

That you can use to install MSET NVRAM rop. I just changed the name of the dat file the payload expects. rxInstaller needs some fixes if you wanted to keep using that. CakeHax submodule replaces old spiderhax/msethax folders.

Also I just tested my build on Ninhjhax. The top screen does show the logo, but bottom screen remains black and it does nothing after that. So just bottom screen address that needs resolved. ;)

**Comment by dukesrg** [comment]
@ApacheThunder 
So how about rxinstall.nds? I'm actually have several small issues left with mset payload and rxinstall.nds on noarmips branch.

**Comment by ApacheThunder** [comment]
As I recall rxinstall.nds needs the decryption code removed (as the mset payload in rxTools.dat is no longer encrypted in CakeHax branch) and the offset for mset 9.x fixed. I don't really know the code behind the patch files very well so I haven't done anything to that. The CakeROP fork I made createa a NDS file that does the same thing rxintall did. I've used it and it works on getting this to boot from downgraded MSET on 9.x.

**Comment by dukesrg** [comment]
So actually rxinstall.nds will be of no use in case rxTools moves to CakeHax loader?

**Comment by ApacheThunder** [comment]
Yeah. Pretty much. Mid-Kid seems to prefer rxinstaller since he thinks the code looks better. But meh. CakeROP NDS file gets the job done. I see no problem using that for CakeHax build.

Also, I don't think CakeROP uses armips (at least for the NDS builder). I don't see references to it in makefile. It stores compiled patch.s in the include folder as a .h file.

**Comment by dukesrg** [comment]
In case of compiled patch I think not a good option :-1:

**Comment by ApacheThunder** [comment]
Also rxTools.dat is only 1.3mb or so for CakeHax version. :D

**Comment by ApacheThunder** [comment]
Well the patches.h file in include is always updated with contents of patches.s during compile. So it's not precompiled if that's what you were thinking.

**Comment by AlbertoSONIC** [comment]
Ok the GUI is finished, so if you tell me that your repo is up-to-date with the latest commit of main repo (less than 5 mins ago), then we can merge ;)

**Comment by Syphurith** [comment]
@ApacheThunder @AlbertoSONIC There are conflicts currently.
Git doesn't count identical files from different commits as the same one if it was changed ever, it only counts some commits as "points" and a ever changed file is changed (No matter reverted or not).
To solve it you may need to rebase your own changes.
If pick commits from another branch and make those after yours, it is different than the original.
So you could do so this way: create a new branch on where these two begins, and take the original one, and then cherrypick yours from your own, and remember to solve conflicts.
Hope this would help you deal with that.

**Comment by motezazer** [comment]
CakeHax was merged by #69 
I close tis pull request.

**Pull request closed without merging**
