### PR TITLE
Update CakeBrah / README

### PR DESCRIPTION
**Pull request by kot2002**

### CODE REVIEW

**Comment by 173210** [comment]
:-1: It's still unstable.

**Comment by kot2002** [comment]
CakeBrah you reverted does not support hax 2.x.
And all other workarounds which attempt to support hax 2.x (ctrbootmanager, bootctr..) use libkhax.

Are you against this because libkhax makes entry unstable on ninjhax 1.1b ?

**Comment by 173210** [comment]
@kot2002 It's unstable even in *hax 2.5. (I'm on *hax 2.5.)

**Comment by kot2002** [comment]
Yes, I get that.
But I think it is better than nothing to support hax 2.x even if somewhat unstable.

mid-kid/CakeBrah@83aaed82b8c7b43ffb2fe4e145774916eaff5e29
: Ninjhax 1.1b support, no 2.x support

mid-kid/CakeBrah@8fccc6d7f0b1fc9f4596effa0e01835b0350f1bd
: Ninjhax 1.1b support, unstable 2.x support

I'd rather choose the latter..

**Comment by 173210** [comment]
@kot2002 "master" branch is getting ready for the new release. You can use https://github.com/AlbertoSONIC/rxTools-experimental or make another branch for now.

**Comment by kot2002** [comment]
Ok, I see. I'm closing this.

**Comment by kot2002** [comment]
But.. You are using ctrbootmanager right? That uses libkhax either :P ...

**Comment by 173210** [comment]
@kot2002 LOL I have no idea why it works.

**Comment by AlbertoSONIC** [comment]
I use ctrBoot (not ctrBootManager) and it boots everytime on N3DS, but often the bottom screen is not shown...

**Comment by urherenow** [comment]
I've been using ctrbootmanager, when I launch from menuhax. Sometimes it fails, but it works at least 8 out of ten tries as long as I hold L when selecting it.

**Pull request closed without merging**
