### PR TITLE
Add PROCESS9_CODE_ADDR

### PR DESCRIPTION
**Pull request by 173210**
This will fix the patch on Process9 for KTR as #244 does.
I have not tested, so please check whether this works.

### CODE REVIEW

**Comment by AlbertoSONIC** [comment]
My MicroSD adapter just died... @motezazer @capito27 can you test this?

**Comment by capito27** [comment]
Just tested, it freezes when launching both emunand and sysnand on my N3DS (tried from Ninjhax 1.x).

**Comment by 173210** [comment]
@capito27 How about before applying this?

**Comment by 173210** [comment]
I close this pull request because the PROCESS9_CODE_ADDR for KTR in this commit is invalid.

**Pull request closed without merging**
