### PR TITLE
CakeHax - Rebased edition.

### PR DESCRIPTION
**Pull request by mid-kid**
I don't know what's up with the double commits, but it works, so hey.

Anyway, I just rebased the pull request from #55 for easy merging.
There's some things, however, that still don't work: For one we have rxinstaller.nds, of which the ROP chain has to be adapted for CakeHax.
Then, we have the draw.h, which I have no idea what you want to do with it, but that's up to you (for now define BOT_SCREEN as BOT_SCREEN2).
About apache's changes, some of them (like decrypting filepack) can be done in a separate pull request. Others, I'll cherry-pick.

There's still some testing to testing to be done before this is finished.

### CODE REVIEW

**Comment by mid-kid** [comment]
Fun fact: It doesn't get past the Loading... screen.

**Comment by mid-kid** [comment]
Nevermind, I didn't have the theme installed. You should consider some proper error messages.

**Comment by AlbertoSONIC** [comment]
So this is automatically mergeable?

**Comment by motezazer** [comment]
Yex, it's based on the latest commit.

**Comment by AlbertoSONIC** [comment]
Then we can merge it!

**Comment by AlbertoSONIC** [comment]
I'll fix ninjhax BOT_SCREEN once i get home

**Comment by motezazer** [comment]
Tested with Ninjhax : works perfectly well!

**Comment by motezazer** [comment]
@AlbertoSONIC Everything works, no need to fix anything.

**Comment by AlbertoSONIC** [comment]
Now it's perfect ;)

**Comment by dukesrg** [comment]
How about rxinstaller, is it working now?

**Comment by motezazer** [comment]
@dukesrg No. And I'm not able to fix it.

**Comment by mid-kid** [comment]
You could use CakesROP instead, but I badly recommend against it, since it's a bunch of copy/paste work in a "just werks™" state.

**Comment by dukesrg** [comment]
@motezazer I'm asking because I'm holding one pool request ftom @173210 int my noarmips branch that allows to transfer all code ftom armips to GAS without exlicit data workaround. The only thing stops me from merging it now and making a pool request intro the main thread is that rxinstalled builds something different and I'm just not able to check if it is working like that. Firm patches compiles the same (well'' except gas generated a different branch opcode in reboothax, but this can be easily tested with SSB)

**Pull request merged**
