### PR TITLE
fill_* tools substituted by dd

### PR DESCRIPTION
**Pull request by dukesrg**
It is much faster and do not need to build additional tools that way.
/dev/zero may be changed to /dev/random or /dev/urandom to get crap generated :)

### CODE REVIEW

**Comment by DarkMatterCore** [comment]
Have you tested it with a dd build for Windows/other OS?

**Comment by dukesrg** [comment]
I only tested with Windows (devkitpro/msys build)

**Comment by DarkMatterCore** [comment]
Cool. This should reduce the compilation problems some people were getting (including myself, I had to use a different MinGW GCC build for these tools for some reason).

**Comment by dukesrg** [comment]
Well, there are several more tools which requires gcc to build for the build machine platform. So additional MinGW/cigwin/msys is required to build. However installing MinGW is very easy IMO.

**Pull request merged**
