### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mariogamer2**

### CODE REVIEW

**Comment by urherenow** [comment]
and while we're at it, @AlbertoSONIC is https://rxtools.ga/3DS/rxTools/Nightlies/ the new official place for nightlies? If so, and we make the change, we should change the link as well.

**Comment by MelonGx** [comment]
Additional notifications about "https://dukesrg.github.io/?mset/rxinstaller.bin" URL:

The "?" question mark in the URL format directs your SD root.
So:
- If you use this URL without any change, your rxinstaller.bin should be placed on SD://mset/. 
-- Otherwise this URL will not boot your rxinstaller.bin.
- If you put rxinstaller.bin outside SD://mset/, you should manually change the URL.
-- For example, if you placed rxinstaller.bin on SD root, then the valid URL should be changed to https://dukesrg.github.io/?rxinstaller.bin.

Need somebody describe this issue in readme.

**Comment by mariogamer2** [comment]
@urherenow didn't think about it,i'll remove.

**Comment by urherenow** [comment]
@mariogamer2 did you look at @MelonGX post? Should have taken care of that too.
On line 73, after it says "Otherwise, on firmwares 9.2 or older visit" add in "9.2 or older, copy rxinstaller.bin to SD:/mset/, and visit..."

**Comment by mariogamer2** [comment]
Ok thank @urherenow I updated.

Also, https://rxtools.ga/3DS/rxTools/Nightlies/ is a part of https://lavanoid.github.io

**Comment by mariogamer2** [comment]
Humm,you are good,I'll add the link.

**Comment by mariogamer2** [comment]
@AlbertoSONIC @nastys this can be merged

**Comment by lavanoid** [comment]
HHHmmm. I put a lot of effort into making the nightlies homepage so I wouldn't appreciate replacing lavanoid.github.io with the directory listing of builds....

**Comment by lavanoid** [comment]
@urherenow No. https://lavanoid.github.io is the place for nightlies. rxtools.ga is just a "CDN". Not replacing my homepage with a crappy dir listing xD

**Comment by urherenow** [comment]
👍
No offense, bro. Confusion in the down time...

**Comment by lavanoid** [comment]
@urherenow  No offence taken :D I got the brain of a 9 year old, don't worry about it xD

**Comment by Shadow322** [comment]
LOL

**Comment by nastys** [comment]
This can't be merged yet...
1) nightlies may only be downloaded from lavanoid.github.io (as @lavanoid has explained above)
2) there are grammar, spelling and syntax mistakes (we've been trying to keep the README as tidy as possible)

**Comment by mariogamer2** [comment]
@nastys first issues fixed
second will be this week-end hopefully,sorry my english is a bu***

**Comment by mariogamer2** [comment]
@lavanoid sorry

**Comment by lavanoid** [comment]
lol

**Comment by mariogamer2** [comment]
Think this is good now ;)

**Comment by lavanoid** [comment]
@nastys ?

**Comment by nastys** [comment]
Fine, except that "3DS" looks better than "3ds". I'll merge and fix it :wink:

**Pull request merged**
