### PR TITLE
Update rxtools/Makefile and transpose the font

### PR DESCRIPTION
**Pull request by 173210**

### CODE REVIEW

**Comment by dukesrg** [comment]
@173210 better now :+1:
I'll check once again if it possible to easy rearrange font image with imagemagick to simplify glyph address calculation.

**Comment by 173210** [comment]
@dukesrg Actually I know a better command. But I'm looking for the better solution...
```
convert unifont-8.0.01.bmp -crop 4096x4096+32+64 -depth 1 -negate -transpose bmp:- | convert -crop 16x4096 -append bmp:- gray:font.bin
```

**Comment by AlbertoSONIC** [comment]
Can I merge?

**Comment by 173210** [comment]
@AlbertoSONIC Yes, of course.

**Comment by dukesrg** [comment]
@173210 if -append writes to the end for gray format, why not? It will make a linear incrementing font data. Most probably you won't avoid using pipe for that operation anyway, so looks fine

**Comment by 173210** [comment]
@dukesrg By the way, does pipe work on Windows? Here is my latest command.
```
convert $< -crop 4096x4096+32+64 -depth 1 -negate -transpose - | convert -crop 16x4096 -append - gray:$@
```

**Comment by 173210** [comment]
So whether this works or not.
https://github.com/173210/rxTools/commit/69609178658dd0dc0234b40c944635e19c98b078

**Comment by dukesrg** [comment]
@173210 it works fine from the shell, but make breaks the pipe

**Comment by dukesrg** [comment]
@173210 Oh, wait, its working just fine!

**Comment by 173210** [comment]
@dukesrg Review #123,

**Comment by dukesrg** [comment]
@173210 Can't find comments from that PR anymore, so I'll repeat here also just in case. This one will change byte order to LSB first, so whole glypth column may be shifted down as one unsigned short with screenbuffer address(y coord) increase
@convert -crop 4096x4096+32+64 -transpose $< - | convert -crop 16x4096 -append - - | convert -roll +8 -negate -depth 1 - gray:$@

**Pull request merged**
