### PR TITLE
Add LICENSE notice again

### PR DESCRIPTION
**Pull request by 173210**

### CODE REVIEW

**Comment by AlbertoSONIC** [comment]
Why? @b1l1s told me to remove pasta license!

**Comment by 173210** [comment]
@AlbertoSONIC BSD 2-clause (and he) just tells to add credits. It doesn't matter to add our license because BSD 2-clause is compatible with GPL.

**Comment by b1l1s** [comment]
Goddamnit. Remove the copyright and the license. The code is not GPL will never be. And it is not 'Copyrighted by PASTA'.

**Comment by 173210** [comment]
@b1l1s You have licensed BSD 2-clause, it admits to license under GPL. Don't you know what the fact that BSD 2-clause is compatible with GPL means?

**Comment by 173210** [comment]
@b1l1s Google suggested a nice article. See this.
http://programmers.stackexchange.com/questions/75436/relicense-bsd-2-3-clause-code-to-gpl

**Comment by b1l1s** [comment]
It doesn't mean that you can add your copyright willy nilly.

**Comment by b1l1s** [comment]
Also show me which modifications were made to patches.S that's worth the relicense.

**Comment by 173210** [comment]
@b1l1s We can, because it includes our codes.

**Comment by 173210** [comment]
@b1l1s See the commit log. We have copyrights of any small changes.

**Comment by b1l1s** [comment]
Oh so we are a footnote in our own files? That's copyrighted by PASTA? Again show me any significant contributions to patches.S that allows you to change the files to GPL.

**Comment by 173210** [comment]
@b1l1s See the commit log. I donated all my changes to the team. And look at the article. It explains well.

**Comment by b1l1s** [comment]
I don't think you've read the article you posted buddy. LOL

**Comment by 173210** [comment]
@b1l1s I've read. Or you may say I'm misunderstanding something.

**Comment by b1l1s** [comment]
I don't think you've read the article you posted buddy. LOL

*By significant, in this case since it's ROP, I need to see a new ROP chain, or major bug fix. Moving files around and changing Makefile doesn't count.

>In order to actually be able to release combined code under GPL other author would have to make "significant contribution" to the code. It's vague what it exactly means, but usually should mean at least adding new significant feature, not just minor patch.

**Comment by 173210** [comment]
@b1l1s So you say our patches doesn't include characteristic (I forgot a translation for the term "個性".)?

**Comment by b1l1s** [comment]
Hell no. If by kosei you mean renaming to rxInstaller then you have that, if by kosei you mean actual meaningful contribution to CakesROP that we ourselves would like to pull to the main repo, I say yes, you don't have the necessary kosei.

**Comment by nastys** [comment]
@173210 Perhaps "personality"?

**Comment by 173210** [comment]
@nastys No, it's the the requirement to have copyrights.

**Comment by 173210** [comment]
This is what I mean.

Threshold of originality
https://en.wikipedia.org/wiki/Threshold_of_originality

**Comment by nastys** [comment]
I think that depends on the law of the country.

**Comment by b1l1s** [comment]
Yeah you don't have that sorry.
So it is decided, no GPL, no PASTA copyright.

**Comment by 173210** [comment]
@nastys It's common to most countries. The current problem is that I think the changes has originality and @b1l1s don't.

**Comment by b1l1s** [comment]
Show me which ones. I'm going out for a bit, I'll check them once I get back.

**Comment by 173210** [comment]
@b1l1s So you can check the commit log.

**Comment by b1l1s** [comment]
I'm not going to do your work for you. List everything that you think is significant here and I'll go through them.

**Comment by nastys** [comment]
You know you can just add your name to the copyright notice, right?

**Comment by 173210** [comment]
Everything on the commit log. (e.g. 9148014dd17ac28ad590c5577827de017fb3ed2d)

**Comment by 173210** [comment]
@b1l1s  If you think this is not enough, you can give me another idea.
```
 * This software was originally licensed by zoogie, mid-kid, bilis, and Reisyukaku
 * under the BSD 2-clause license. See LICENSE for the details.
```

**Comment by b1l1s** [comment]
> Everything on the commit log. (e.g. 9148014)

No, which part of that has anything to do with ROPs?

> @b1l1s If you think this is not enough, you should give me another idea.

Yes that's enough, without PASTA copyright, without GPL license.

>You know you can just add your name to the copyright notice, right?
Unless you really hate the GPL...

I do, but that's besides the point. The point is you have no claim of copyright or in this case significant contribution to change the license to GPL. What if I take one of your files and slap my own copyright and license on it, put you as the contributor as the footnote of the license?

**Comment by 173210** [comment]
I think the easiest way is to add something which can convince @b1l1s that it's a significant change. Probably the hurdle is not so low. LOL

**Comment by b1l1s** [comment]
Instead of trying to GPL CakesROP files, which is already licensed, why don't you guys go spend time and fix all the bugs in rxTools instead, it's not rxCfw you know. Maybe fix the missing original copyright notices from the tools sources too.

**Comment by 173210** [comment]
@b1l1s I'm cleaning up all codes in rxTools. Of course, rxinstaller is not an exception.
Please open a new issue if you found missing notices. I don't know the origin of tools (except themetool) at all and I have not added the notice of PASTA copyrights nor the original one. If you know the origin, please tell me.

**Comment by b1l1s** [comment]
Sorry tools as in the rxTools folder, and I only know of draw.c because the author mentioned it to me, that you guys do not comply with GPL but is somehow happy with GPLing the whole rxTools.

**Comment by 173210** [comment]
@b1l1s I added GPL license because rxTools didn't have a particular license (although it seems to be licensed under BSD 2-clause) . rxTools developers may have not concerned about those licenses well.
So we need to solve those problems. If you found a license problem, please open an issue.

**Comment by b1l1s** [comment]
You need to solve the problem, you opened the can of worms. Sorry but it had to be said.

**Comment by 173210** [comment]
@b1l1s Yes, probably. xD

**Comment by b1l1s** [comment]
Still not seeing the removal of GPL in the source files. Please acknowledge that you understand what I'm asking at least, even if you don't want to do it.

**Comment by 173210** [comment]
@b1l1s I know there are still conflicts. Now the problem is whether we have copyrights for our changes. It doesn't interfere the copyrights of the authors of the original version and we don't have to remove it. You can just ignore the notice if you think it's invalid.

**Comment by b1l1s** [comment]
I take that as an acknowledgement.

> we have copyrights for our changes

Your changes were made under the false assumption that the code is under GPL and owned by Pasta when it wasn't. Since they are all trivial changes, just revert them back if you don't want them under BSD 2-Clause.

> You can just ignore the notice if you think it's invalid.

Funny, then what's the use of a license and copyright in the first place?

**Comment by 173210** [comment]
> Your changes were made under the false assumption that the code is under GPL and owned by Pasta when it wasn't.

No, I myself suggested the team to own the entire source code (or all changes in this case) .

> just revert them back if you don't want them under BSD 2-Clause.

I don't know why it makes difference.

> Funny, then what's the use of a license and copyright in the first place?

To claim our own rights. And you deny it. That's all.

**Comment by b1l1s** [comment]
You can add your own copyright for your changes obviously, but under BSD 2-Clause license. That's it. Easy peasy.

**Comment by 173210** [comment]
@b1l1s It doesn't make sense. When I don't have the copyright for my changes, I can't apply any license. It's a simple theory, isn't it?

**Comment by b1l1s** [comment]
You have copyright for your changes, but not enough leeway to change the license to GPL.

**Comment by 173210** [comment]
@b1l1s Is the standards different? I have not such a clause in BSD 2-clause.

**Comment by b1l1s** [comment]
LOL And you were the one that gave me the link, now you're arguing against it. Your copyright is for the *changes* not the whole file! And under BSD 2-Clause. Not that difficult to understand.

**Comment by 173210** [comment]
@b1l1s I thought "significant difference" means "threshold of originality", and you didn't deny it, right?
Of course, I have not the whole file, but GPL is compatible (it means GPL doesn't interfere with) BSD 2-clause, so I can apply the license. Do you really understand what "compatible" means?

**Comment by Syphurith** [comment]
@173210 @b1l1s I may have a plan. Yes, rxinstaller, and cakehax are from b1l1s and rei and other, and licensed as BSD2. JSMN under MIT. Main project is from Decrypt9, under GPL. PolarSSL under GPL too. Surely rxinstaller is edited a bit to fit the "rxTools.dat", that is modified.
@b1l1s If you don't want a new compatible license be added, you may provide a submodule and this serves "rxTools.dat" `(maybe just let it replace the string with 'make xxx' when compilition)`. Thus modified version of Cakes' installer could be avoided, and this repo in your control, just BSD2.
I do think we should only license our code under GPL, and have other sources' stated.
I don't know if my opinion is correct this time. This is just a plan.

**Comment by b1l1s** [comment]
http://www.groklaw.net/articlebasic.php?story=20070927103522813

>Common attempts by developers at stating dual license notices tend to be confusing, contradictory, and legally unclear. While there may be cases where it will make sense for a developer (with a knowledgeable lawyer’s assistance) to place a dual license on his code, we generally recommend that developers not use dual licensing if their goal is simply to allow recipients to use the code within larger GPL’d works as well as under permissive terms. If such a developer is using a license like the modified BSD license or the ISC license, where there is an established and widespread community understanding that the terms permit incorporation into larger programs covered by the GPL, the developer should simply use the permissive license without any further reference to the GPL.

I deny your claim to significant changes. Yes.

**Comment by b1l1s** [comment]
@Syphurith We already allow custom rop names. But no one wants to use that.

**Comment by 173210** [comment]
@b1l1s It means you deny my copyrights, doesn't it?

**Comment by b1l1s** [comment]
You have claim to copyright, under BSD 2-Clause. I deny your claim to significant changes.
*Repeating to make myself clear.

The link above is what is meant by compatibility BTW. BSD 2-Clause is compatible to be used in a GPL codebase, GPL on the hand is not.

**Comment by Syphurith** [comment]
@b1l1s Cause just force user to make a text file isn't friendly for a usable product. I dislike such way.
Not so difficult for such a feature, just let us 'make LAUNCH_DAT=rxTools.dat' or other is ok, and user would not know that and yes without manually added text file. And this part could be totally BSD.

**Comment by b1l1s** [comment]
@Syphurith I can do that sure.

**Comment by Syphurith** [comment]
@173210 @b1l1s I'm getting confused. Two question, just True or False first:
1. BSD licensed code could be used in a GPL project.
2. BSD licensed code could be relicensed to GPL.
Please answer and provide the proof. (well i personally think that is T,F)

**Comment by Syphurith** [comment]
@b1l1s Then please do that. Eh.. any other conlicts between you?

**Comment by 173210** [comment]
@Syphurith I don't answer because it just makes it clear the conflicts. Google and find the answer yourself.

In technical term, your suggestion does make the best sense.

**Comment by b1l1s** [comment]
@Syphurith Right, T,F(with exception when significant contribution has been made, even then it's weird)

**Comment by Syphurith** [comment]
@173210 thanks. I would search for the answer myself.
So you think let b1l1s make that feature to let us just include the repo as submodule is ok?

**Comment by b1l1s** [comment]
@Syphurith Also I'll do it later today.

**Comment by b1l1s** [comment]
There we go : https://github.com/mid-kid/CakesROP/commit/19c2629deef196b49b3d5a43d12b44b86f3eda5f

**Comment by 173210** [comment]
@b1l1s Thanks, but our path is longer than MAX_DATNAME_LEN (24 > 16) . Can you add an option to show an alternative string?

**Comment by b1l1s** [comment]
https://github.com/mid-kid/CakesROP/commit/616ea0a1fa472edd8cab57f5486ecb5bf24d0c1e

That's the first part, I don't know what you mean with the 2nd.

**Comment by b1l1s** [comment]
https://github.com/mid-kid/CakesROP/commit/e0968e2d17fd959f89e7d2cef757e10672d0f73e

**Comment by b1l1s** [comment]
Anyone mind telling me what's going to happen to this now? You have two options that I can think of :
1. Use the changes I made and add CakesROP as a submodule.
2. Use BSD 2-Clause license for rxInstaller.

Option 1 (@Syphurith's solution) should be the easiest and the best, you don't have to manually pull changes from CakesROP anymore.
Option 2 means that you have to contact all contributors who made any changes to rxInstaller since rxTools got changed to GPL and notify them that their contributions will have to be relicensed under BSD 2-Clause. If they disagree you have to revert and redo the changes.

**Comment by nastys** [comment]
If no one decides by the end of the day, I'll go for the first option.

**Comment by b1l1s** [comment]
Understood. Tell me if you need any more changes to CakesROP to make it work with rxTools.

**Comment by 173210** [comment]
Thanks.

**Comment by nastys** [comment]
@b1l1s Actually, nobody touched rxInstaller after this PR has been merged, so...
What about reverting it?

**Comment by nastys** [comment]
Tomorrow I can't add CakesROP as a submodule, so I'll just revert this PR temporarily.

**Comment by b1l1s** [comment]
I meant any changes since rxTools got re-licensed to GPL. Way back when. You're adding the submodule tomorrow anyway so that should be fine though.

**Comment by nastys** [comment]
@b1l1s Please tell me what to do, or simply send a Pull Request.
Tomorrow I won't be at home until night, so I'll fix this later tomorrow or the day after.

**Pull request merged**
