### PR TITLE
Translation for all features

### PR DESCRIPTION
**Pull request by dukesrg**
Almost all features are ready to be translated with external json files (a part of downgrade app is WIP)
Added workaround to make rxTools boot with no external font and any translation with minimum diagnostic messages (ability to open menu in this mode should be considered)
Unless Issue #119 is not solved it is strongly *not recommended* to merge this into master - included en.json is above the limit.

### CODE REVIEW

**Comment by AlbertoSONIC** [comment]
"Unless Issue #119 is not solved it is strongly not recommended to merge this into master - included en.json is above the limit."

Maybe I should have read this before merging ;)
Anyway, merge reverted

**Comment by dukesrg** [comment]
@AlbertoSONIC two days in a row ;)
It's time for branches! :)

**Comment by dukesrg** [comment]
@soarqin please review en.json, maybe we need to rephrase several format strings to be compatible with chinese translation.

**Comment by soarqin** [comment]
it is okay to keep current translation file coz chinese grammar is flexible enough to handle it

**Comment by dukesrg** [comment]
@soarqin do you mean current pool request translation file by current or the old one?

**Comment by soarqin** [comment]
@dukesrg I mean the one in PR

**Pull request merged**
