### PR TITLE
fixed ImageMagick compatibility, updated Readme.md and Makefile bug

### PR DESCRIPTION
**Pull request by dukesrg**
- Added a workaround for the latest ImageMagick version bug (checked with ImageMagick 6.9.1--7 and 6.9.3-3 Q16 x64)
- Updated and rearranged build requirements in Readme.md
- Fixed recently added Makefile issue in Windows

### CODE REVIEW

**Comment by mariogamer2** [comment]
For me,on linux and latest image magick, I just applyed these change: https://github.com/roxas75/rxTools/pull/415

**Comment by RandomIntermition** [comment]
@mariogamer2 that pull was canceled because it fixed the same bug that this fixes. it just does it using brackets rather than a rename and includes a series of other fixes, so best just waiting until this is merged then rebuilding. shouldn't encounter any errors.

**Comment by mxalbert1996** [comment]
I applied this and built on Ubuntu with ImageMagick 6.9.3-3 but it always displays like this:
rx_bug
Could boot Emunand but the UI is broken. Tried many times on O3DS and N3DS. I built e2c1e58 with ImageMagick 6.9.2-10 and it was OK.

**Comment by mxalbert1996** [comment]
Built this commit on Ubuntu with ImageMagick 6.9.3-3 and the UI is broken. Tested on O3DS and N3DS many times and it always displayed like this.
rx_bug
Built
33858cd with ImageMagick 6.9.2-10: No problem.
1913cbb with ImageMagick 6.9.2-10: No problem.
1913cbb with ImageMagick 6.9.3-3: Broken UI.

**Comment by dukesrg** [comment]
@mxalbert1996 that means theme files generation is already broken in 9.3.3-3, didn't check that, only fixed font for now. Just stay on 9.2, I'll check how to fix theme generation tonight.

**Comment by capito27** [comment]
@dukesrg i have confirmed this compiles fine in windows (no warped theme files), shall i wait for you to finish checking theme generation on linux before merging or not ?

**Comment by dukesrg** [comment]
@capito27 I only have a windows toolchain. Anyway this PR won't affect theme at all, so you can merge.

**Comment by dukesrg** [comment]
@capito27 Checked theme with 6.9.3-3 and 6.9.3-4 - canvas size with raw formats are totally messed up. Any operation involving canvas resize (rotate, transpose etc) causes resulting theme file to be of size 320x320 (while verbose reports it is 240x320). Can't workaround it with page/repage/size/crop, it is just not working as intended. So, for now #397 and #412 should be closed, because actually font generation was adopted. Or at least merged in one and renamed with something like "ImageMagic bugs".

**Pull request merged**
