### PR TITLE
Introduce TMIO driver

### PR DESCRIPTION
**Pull request by 173210**

### CODE REVIEW

**Comment by AlbertoSONIC** [comment]
Are you really really really really sure this works fine?

**Comment by urherenow** [comment]
I was just staring at this and wondering what the command line is to pull it onto my computer so I can build it and see what breaks... Do I need to do it manually?

**Comment by 173210** [comment]
@AlbertoSONIC Really sure. I have tested so many times because it has many changes.
@urherenow
```shell
git fetch https://github.com/173210/rxTools.git master
git checkout FETCH_HEAD
```

**Comment by urherenow** [comment]
It builds fine. Any particular way I need to test launching it or some functionality I should check?

**Comment by urherenow** [comment]
There are still so many compiler warnings in the code such as these:

x:/devkitPro/devkitARM/projects/rxTools/include/svc.h:26:25: warning: return type defaults to 'int' [-Wimplicit-int]
 static inline _Noreturn svcExitThread()
                         ^
source/payload/arm9/thread/thread.c:56:8: warning: return type defaults to 'int' [-Wimplicit-int]
 static patchLabel()
        ^
source/payload/arm9/thread/thread.c: In function 'patchLabel':
source/payload/arm9/thread/thread.c:88:6: warning: 'return' with no value, in function returning non-void
      return;

**Comment by AlbertoSONIC** [comment]
@173210 Yeah I know, that's why I asked...

I've tested it aaaaaand......... Got three freezes... It doesn't work. And I merged it :/

**Comment by AlbertoSONIC** [comment]
rxTools never boots its UI, the 3ds just freezes on a black screen...

**Comment by urherenow** [comment]
yup. USA N3DS. Black screen from ctrbootmanager.

**Comment by urherenow** [comment]
But I have tested building with the latest Cakehax and Cakebrah with devkitpro r45 (with the included ctrulib 1.0 and all) and it works perfectly. I don't understand why we aren't updating those submodules to use the latest tools. Whatever problems newer Cakehax was causing in the past, I don't think will happen right now since we have the Cakerop as a separate module at a specific commit.

So, leave CakesROP alone, but use the latest CakeHax and CakeBrah, along with updating to devkitarm r45 gets a big thumbs up from me.

**Comment by AlbertoSONIC** [comment]
Ok I'll try ;)

**Comment by AlbertoSONIC** [comment]
My extremely slow internet connection doesn't let me download devkitpro r45...

**Comment by urherenow** [comment]
Just use the updater. It shouldn't download much if r44 is already installed.

**Comment by 173210** [comment]
Well, you may test SDMC/NAND IO. I've tested with MSET downgrader, FBI injection, and NAND dumper.

**Comment by urherenow** [comment]
@173210 how and on o3ds or n3ds? This commit completely broke rxtools. No data installation suite, no menu. Only black screen. USA N3ds.

**Comment by 173210** [comment]
@urherenow Both on my old and new one. Anything use those devices, so the symptom is convincing, if the driver is corrupted.
Another possibility is corrupted ARM binary. The compile option has been changed to compile for ARM state because the TMIO driver uses `mcr` instruction.

**Comment by urherenow** [comment]
Well, then you either didn't do a make clean, or you've introduced another build problem that breaks Windows because neither I nor @AlbertoSonic can run rxtools from this source.

**Comment by 173210** [comment]
@urherenow The OS shouldn't matter. The toolchain may do, but everyone uses devkitARM, right?

**Comment by urherenow** [comment]
Yes. Trying to build without devkitARM would be frankenstein's nightmare...

**Comment by urherenow** [comment]
@173210 Here's a text of my build. See if you spot anything fishy (and maybe see about some of the compiler warnings?). Either way, this simply does not run. I don't know how you say it's been working for you. Did you delete your whole 3DS /rxtools folder and set it up from scratch?

[Build.txt](https://github.com/roxas75/rxTools/files/79477/Build.txt)

**Comment by 173210** [comment]
@urherenow Well, nothing is fishy. It's completely fine. No, I have not deleted the directory. I just simply overwrote `code.bin`.

**Comment by urherenow** [comment]
Check my post again. Build2.txt

**Comment by 173210** [comment]
@urherenow Can you set `V=1` for make?
```shell
make all-target-rxtools V=1
```

**Comment by urherenow** [comment]
Here it is. and since I only ever build by "make release", I'll try what I just built to see if it works or not.
[testbuild.txt](https://github.com/roxas75/rxTools/files/79488/testbuild.txt)

**Comment by urherenow** [comment]
Still a black screen

**Comment by urherenow** [comment]
Bump.
Sooo... @AlbertoSONIC are you going to revert this or what? @173210 and 1 other person insists that it works for them, so I seriously doubt anybody is looking into what went wrong.

**Comment by AlbertoSONIC** [comment]
Honestly I don't know. I believe in @173210 , if he tells me he'll fix this then it's ok, otherwise I must revert... 

Btw, I think 173210's 3dses are special... Everything always works on them xD

**Comment by urherenow** [comment]
edited my post. read again please. Late for work...

**Comment by AlbertoSONIC** [comment]
I'm using devkitpro r45 with latest cakehax, cakebrah and libkhax. And it's not working.

Well, actually I'm still using the old 3dsx, but I think it's not related...

**Comment by urherenow** [comment]
If you cloned Cakebrah separately (and recently), go into the Cakebrah folder and: git checkout 04dbd5c
Then go back to rxtools and make clean, then make release and see if that gets rid of the black screen or not.
That's what I planned on trying during my lunch anyway...

**Pull request merged**
