### PR TITLE
Introduce TMIO driver

### PR DESCRIPTION
**Pull request by 173210**
Introduce TMIO driver instead of old sdmc.s
Build for ARM state, but use Thumb library because sbrk of ARM newlib
in devkitPro doesn't work.

This commit also updates FatFs library.

\# Conflicts:
\#	rxtools/stub.ld

Commit 0733322dfdf0588c4908d1e50e974e8dfba6d91c used 932 _CODE_PAGE, which caused a compatibility problem.
In this commit, _CODE_PAGE is defined as 437.
See #336, #338, #340, and #341.

### CODE REVIEW

**Comment by urherenow** [comment]
This works :)

**Comment by Shadow322** [comment]
This being merged yet?

**Comment by 173210** [comment]
@Shadow322 This is a fixed version.

**Comment by Shadow322** [comment]
"Fixed" version I don't understand

**Comment by 173210** [comment]
@Shadow322
> Commit 0733322 used 932 _CODE_PAGE, which caused a compatibility problem.
> In this commit, _CODE_PAGE is defined as 437.

**Comment by AlbertoSONIC** [comment]
So I can merge this?

**Comment by Desterly** [comment]
If the only difference here is the code page setting, I've been using it in my builds for the past week and haven't had any issues.

**Comment by urherenow** [comment]
Yes. Works for me 👍

**Pull request merged**
