### PR TITLE
Fixes for KTR

### PR DESCRIPTION
**Pull request by 173210**
a79676a5a502811804e013861a912c19efb71945:
Please confirm that it works with extended RAM games before merging.

/* I'm planning to add a patching feature to the reboot function. We don't have to write a patched code to SD card and eventually solves CheckInstallationData. At first, I'll unify the rebooting code. The current code base has two rebooting code in reboot.bin and native_firm.elf. It makes difficult to modify them. */

ec398daf6a0ef519014451f35a99fd670dd6e070, e78cc41b188e1df848ef3519c5bf4901839ea85c:
These fixes don't affect on binaries.

### CODE REVIEW

**Comment by kot2002** [comment]
a79676a5a502811804e013861a912c19efb71945
Does not work with extended RAM games.

**Comment by Syphurith** [comment]
@kot2002 What? CTR is affected? IIRC KTR should be for new 3ds..

**Comment by kot2002** [comment]
@Syphurith Reboot patch is for just O3DS.

**Comment by Syphurith** [comment]
@kot2002 Oh I know now. Thanks for pointed out my mistake.

**Comment by 173210** [comment]
Thank you for reviewing. I'll close this pull request for now.

**Pull request closed without merging**
