### PR TITLE
Use libkhax for compatibility and stability.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by AlbertoSONIC** [comment]
I'll merge once there will be n3ds support ;)

**Comment by Steveice10** [comment]
Fair enough. I haven't really been able to work on N3DS support myself as I don't have one.

**Comment by WilliamO7** [comment]
Bottom screen offsets aren't working on O3DS :(
It does however boot faster, so if this can be pulled off, it would be amazing!

**Comment by Steveice10** [comment]
Bottom screen offsets do work when launched through homebrew launcher, just not directly as boot.3dsx through themehax for some reason. Probably something related to the hardcoded offsets, as CakeBrah's bottom screen works fine.

**Comment by Steveice10** [comment]
Just updated to use libkhax as a submodule.

**Comment by Steveice10** [comment]
Should work on N3DS now.

**Comment by Steveice10** [comment]
Closing as you've moved to CakeBrah.

**Pull request closed without merging**
