### PR TITLE
Now the FindApp() function will always use the most recent TMD/conten…

### PR DESCRIPTION
**Pull request by DarkMatterCore**
…t file combination found in NAND. This fixes a bug in the FBI injection procedure where the application uses a wrong H&S version number if there's data from more than one H&S version in the NAND.

### CODE REVIEW

**Comment by roxas75** [comment]
I cannot merge becouse i accidentally merged dukesrg commit before yours.
He actually passes al the drives as an int now.
Can you update your code to be based on the latest update?
Thanks for the hard work

**Comment by Syphurith** [comment]
Before merge: checkout the latest, and rebase, solve conflicts, push unknown changes.

**Comment by dukesrg** [comment]
Oops, sorry, I thought that it was already merged :(
Anyway there is only drive var needs to be changed with int and %s with %d in sprintf, the rest should be merged automatically on rebase

**Comment by roxas75** [comment]
Do i have to rebase it?
Or is it a thing that can do DarkMatterCore?

**Comment by dukesrg** [comment]
It's a hint for DarkMatterCore, keep master branch intact :)

**Comment by DarkMatterCore** [comment]
Don't worry, I'll update it ASAP.

**Comment by DarkMatterCore** [comment]
It should be ready to go now.

**Pull request merged**
