### PR TITLE
Rewrite rxtools/Makefile

### PR DESCRIPTION
**Pull request by 173210**
I got mad with devkitPro's template and rewrote the Makefile.
It was so verbose, so I also make it shut up.

I have NOT tested on Windows.

### CODE REVIEW

**Comment by AlbertoSONIC** [comment]
I'm not at home until 30th... Can someone test this on windows?

**Comment by urherenow** [comment]
Sorry, I don't think Ican because I updated devkitpro to r45. Libkhax needs fixes...

**Comment by 173210** [comment]
@urherenow Anybody doesn't write correct C. ┐(´д｀)┌

**Comment by FONZD** [comment]
Where can i find IM_MOD_RL_bin_.dll ?

Did you use imagemagick 6.9.2-Q16 ?

**Comment by 173210** [comment]
```shell-session
$ convert -version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2015-10-23 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib
```

**Comment by urherenow** [comment]
Weird... on Windows and a tree that just worked with devkitpro r45, I just replaced the 4 files that were changed and I get:

cp: cannot stat `rxtools/CakeHax/LICENSE.txt': No such file or directory
make: *** [release-licenses] Error 1

even though the file is clearly there...

**Comment by 173210** [comment]
@urherenow So, is there LICENSE.txt?

**Comment by urherenow** [comment]
There is, you just need to change line 78 to:
@cp CakeHax/LICENSE.txt $(RELEASE)/LICENSE_CakeHax.txt

but now I'm getting errors from your reboot.S:

source/features/reboot.s: Assembler messages:
source/features/reboot.s:33: Error: invalid operands (*UND* and *ABS* sections) for `&'
source/features/reboot.s:34: Error: invalid operands (*UND* and *ABS* sections) for `&'
make[1]: *** [/x/devkitPro/devkitARM/projects/rxTools/build/rxtools/features/reboot.o] Error 1
make[1]: Leaving directory `/x/devkitPro/devkitARM/projects/rxTools/rxtools'
make: *** [all-target-rxtools] Error 2

**Comment by 173210** [comment]
@urherenow I got it. You have not properly applied 10c93797195a031953187f85f50e4dedcb41f79e.
Try this:
```
git submodule update --init --recursive
```

**Comment by urherenow** [comment]
submodules have nothing to do with reboot.S,

**Comment by 173210** [comment]
@urherenow You should clone CakeHax in `rxtools` directory to compile. Do the command.
I guess you have the error because Windows ignore the case of the character. It should be `reboot.S`, not `reboot.s`. Rename the file manually.

**Comment by urherenow** [comment]
weird again, the lower case s was a problem as well. Now I need to update my imagemagic to continue, but my wife says it's time to leave :(. Will work on this later...

**Comment by 173210** [comment]
The ImageMagick issue is probably because of the broken shell.

```
convert -crop 4096x4096+32+64 -transpose unifont-8.0.01.bmp - | convert -crop 16x4096 -append - - | convert -roll +8 -negate -depth 1 - gray:/c/Users/root3/Documents/GitHub/rxTools/build/rxtools/font.bin
convert: no encode delegate for this image format `GRAY;C' @ warning/constitute.c/WriteImage/1171.
```

Maybe
```
gray:/c/Users/root3/Documents/GitHub/rxTools/build/rxtools/font.bin
```
becomes
```
gray:C:\Users\root3\Documents\GitHub\rxTools\build\rxtools\font.bin
```
ImageMagick will parse this like the following
```
Part 0: gray
Part 1: C
Part 2: \Users\root3\Documents\GitHub\rxTools\build\rxtools\font.bin
```

I'm just laughing.

**Comment by 173210** [comment]
So, here is the dirty hack to solve the issue.
```
$(call Q,CONVERT,$@)cd $(dir $@);convert -crop 4096x4096+32+64 -transpose $(abspath $<) - | convert -crop 16x4096 -append - - | convert -roll +8 -negate -depth 1 - gray:$(notdir $@);
```

**Comment by 173210** [comment]
And the next problem is.... broken make. xD
```
        MAKE    CakeHax
make[2]: Entering directory `/c/Users/root3/Documents/GitHub/rxTools/rxtools/CakeHax'
make[3]: Entering directory `/c/Users/root3/Documents/GitHub/rxTools/rxtools/CakeHax/rop3ds'
      0 [main] make 3500 open_stackdumpfile: Dumping stack trace to make.exe.stackdump
make[3]: *** wait: No children.  Stop.
make[3]: *** Waiting for unfinished jobs....
make[3]: *** wait: No children.  Stop.
make[2]: *** [/c/Users/root3/Documents/GitHub/rxTools/build/rxtools/CakeHax/mset_4x/rop.dat] Error 2
make[2]: Leaving directory `/c/Users/root3/Documents/GitHub/rxTools/rxtools/CakeHax'
make[1]: *** [/c/Users/root3/Documents/GitHub/rxTools/build/rxtools/code.bin] Error 2
make[1]: Leaving directory `/c/Users/root3/Documents/GitHub/rxTools/rxtools'
make: *** [all-target-rxtools] Error 2
```

**Comment by 173210** [comment]
```
$(call Q,MAKE,CakeHax)cd $(BUILD);$(MAKE) dir_out=. dir_build=./CakeHax name=$(notdir $@) filepath=$(SYS_PATH)/ -C $(abspath CakeHax) bigpayload
```

LOL

**Comment by 173210** [comment]
Ok, 555496e500ef76df79811de915fd2a2366c8f6a4 is the really __dirty__ hack for Windows.
But I __highly__ recommend to stop to use the broken OS.

**Comment by urherenow** [comment]
Will NEVER happen. Over 80% of all businesses use the OS. Your changes will never get commited unless it builds on Windows.

**Comment by 173210** [comment]
@urherenow 555496e500ef76df79811de915fd2a2366c8f6a4 is the one which allow you to build on Windows.

> Over 80% of all businesses use the OS.

s/bussiness/office/

**Comment by AlbertoSONIC** [comment]
So this can be merged now? :P

**Comment by 173210** [comment]
:+1:

**Comment by Shadow322** [comment]
What do I need to update in devkitpro to compile correctly?

**Comment by urherenow** [comment]
Nothing if you haven't updated yet. If you've installed the latest, you need to grab the latest versions of Cakebrah and Cakehax, or look at their respective latest commits and make those changes yourself. I forgot why the rxtools devs don't want to keep those up to date. I vaguely remember some issues with black screens and such. If that's the case, then it's better to just make the changes that make them build with ctrulib 1.0 (and by the way, you should manually download the latest ctrulib tree and "make install" that sucker.

**Comment by urherenow** [comment]
There are still issues. So much for being ready to commit:
make[1]: Entering directory `/x/devkitPro/devkitARM/projects/rxTools/rxmode'
make[1]: *** No rule to make target `/x/devkitPro/devkitARM/projects/rxTools/build/rxmodektr/native_firm.elf', needed by `all'.  Stop.
make[1]: Leaving directory `/x/devkitPro/devkitARM/projects/rxTools/rxmode'
make: *** [all-target-patches] Error 2

**Comment by urherenow** [comment]
@AlbertoSONIC @173210 ok, I'm done figuring it out. Post above has fixes for rxmode/Makefile, then it builds. But I'm worried about the bigpayload warning... should I be?

Then there are the needed updates to CakeBrah and CakeHax for building in devkitpro r45. Since those are submodules and you don't want to fork them for rxtools, why not use the latest trees? I forgot what issues there were that made you want to use older branches...

**Comment by urherenow** [comment]
Sorry to post yet again, but even though I can build this now, and I rolled back to devkitARM r44 and ctrulib 0.6.0, I am unable to run rxtools via any method on my N3DS. @173210 does your build run? On an N3DS? Is this a Windows problem?

**Comment by 173210** [comment]
@urherenow Sorry, I forgot to commit the change. I made a pull request to fix it.

**Comment by 173210** [comment]
@urherenow Confirmed. It doesn't work on my new 3DS.

**Comment by 173210** [comment]
Identified: The issue is in 555496e500ef76df79811de915fd2a2366c8f6a4. It output intermediate files in the source directory.

**Comment by AlbertoSONIC** [comment]
convert.exe: unable to open image `gray;..\build\rxtools\font.bin': No such file or directory @ error/blob.c/OpenBlob/2701.
make[1]: *** [../build/rxtools/font.bin] Error 1
make[1]: Leaving directory `/z/rxTools/rxtools'
make: *** [all-target-rxtools] Error 2

I can't get rxTools to compile due to this :(

**Comment by 173210** [comment]
@AlbertoSONIC It's not a problem of this pull request, but #326.
Anyway, it works fine on my PC.
```
>convert -version
Version: ImageMagick 6.9.1-3 Q16 x86_64 2015-07-01 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: DPC OpenMP
Delegates (built-in): autotrace bzlib cairo fftw fontconfig freetype fpx gslib jbig jng jpeg lcms lzma pangocairo png ps rsvg tiff webp x xml zlib
>where convert
C:\cygwin64\bin\convert.exe
```

**Comment by urherenow** [comment]
He didn't copy convert.exe from image magic to devkitARM/bin

**Comment by AlbertoSONIC** [comment]
@173210 I also get this...

C:\Users\Alber>convert -version
Version: ImageMagick 6.9.2-6 Q16 x64 2015-11-14 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib cairo freetype jng jp2 jpeg lcms lqr openexr pangocairo png ps rsvg tiff webp xml zlib

C:\Users\Alber>where convert
C:\Program Files\ImageMagick-6.9.2-Q16\convert.exe
C:\Windows\System32\convert.exe

**Comment by AlbertoSONIC** [comment]
@urherenow What?

**Comment by 173210** [comment]
So it seems because your ImageMagick is neither Cygwin nor MinGW. Hmm...

**Comment by AlbertoSONIC** [comment]
But it has always worked before...

**Comment by 173210** [comment]
@AlbertoSONIC Even a broken system doesn't always crash.

**Comment by urherenow** [comment]
Nevermind me. I was in a super rush earlier and reading and typing on my phone. At first glance it looked like an issue someone else had before in the gbatemp building thread, that wasn't familiar with paths, so we just had him copy convert.exe to devkitARM/bin as a sloppy fix.

Sorry about that.

**Comment by urherenow** [comment]
Is imagemagic in your path BEFORE system32?

**Comment by 173210** [comment]
@urherenow It should be OK.
```
No such file or directory @ error/blob.c/OpenBlob/2701.
```
This is obviously ImageMagick.

**Comment by urherenow** [comment]
Sorry I can't help much, I'm away from home for the new year... Is there another Makefile for the theme? If so, it can be fixed there.

**Comment by AlbertoSONIC** [comment]
I'll try to reinstall ImageMagick...

**Comment by 173210** [comment]
@AlbertoSONIC Installing the same thing doesn't make sense.
@urherenow Which ImageMagick are you using?

**Comment by Syphurith** [comment]
@173210 For the ImageMagick I've experienced something similar before, that the line refuse to produce the font binary as expected, throwing errors. Seems the `-` mark could not be used to express a former result on windows, even I've tried it with MinGW/MSYS2. And i splitted the line to multiple commands and executed those one by one, and after the font.bin produced I can use `make` to continue the build. *May be cause the pipe commands.* Haven't tried new Makefile in repo.

**Comment by 173210** [comment]
We may have to take the radical solution: remove the broken shell or ImageMagick dependencies in rxTools.

**Comment by urherenow** [comment]
I'm not at home now, so I can't check. Why would you make a pull request without checking it first?

**Comment by AlbertoSONIC** [comment]
@urherenow Make or merge?

**Comment by 173210** [comment]
@urherenow
* __It works fine on Linux.__
* It takes so long to boot my Windows.

@AlbertoSONIC Maybe #327 is a solution for preventing from merging those pull requests.

**Comment by urherenow** [comment]
Both. But I am really hating github on mobile right now. No edit button, just now noticed that it was @Syphurith that said he hadn't tried the new Makefile changes yet... I need to stop replying here until I'm in front of my PC.

**Comment by urherenow** [comment]
@173210 it takes my desktop less than 20 seconds to boot WindowS 10. You using a VM or Wine or something?

**Comment by AlbertoSONIC** [comment]
@173210 Yeah definitely... But it's up to @lavanoid to implement it...

Also, I'd be glad to leave Windows 10, if only I didn't format the HDD in GPT + UEFI firmware... Installing Linux (in dualboot with Win, needed for school) is such a pain...

**Comment by urherenow** [comment]
@173210 remove broken shell or image magic? Nothing was broken until you decided you didn't like the makefiles.

**Comment by AlbertoSONIC** [comment]
@urherenow It takes 3 mins on my laptop :/
Intel Core i7-4700HQ@2.4GHz
8 GB ram
Nvidia Geforce GTX 760M (2GB)
HDD 750GB 7200rpm
Windows 10 Pro installed 1 week ago, no bloatware

**Comment by 173210** [comment]
@urherenow My Windows is broken, maybe because of Insider Preview.
```
Nothing was broken until you decided you didn't like the makefiles.
```
That's right. Any machine is not broken unless we use.

**Comment by urherenow** [comment]
I'm not talking about machines. Rxtools could build on all machines until you messed with the makefiles. I don't see what the value was for your changes.

@AlbertoSONIC an SSD does wonders for speed.

**Comment by lavanoid** [comment]
Will implement that build system when I can stop sleeping so much. Some peeps call me a vampire because I got habits of sleeping throughout the day. *cough* @nastys

**Comment by AlbertoSONIC** [comment]
@urherenow Well, with @173210 changes the build output is much nicer! 

@lavanoid xD

**Comment by 173210** [comment]
@AlbertoSONIC It's just a metaphor. The previous one didn't use those features, so it has no problem.
f5096d5ddead1978ca6713087eb6100f524f964f will output in a directory only for building, so you can assume that there are only source files and use tools such as `grep` easily. Also you can completely clean your repository by deleting the directory.

**Comment by urherenow** [comment]
ok, I'm home now. Happy New Year from Japan!
Anyway, with a fresh clone I have the same issue. It's not an imagemagic problem, it's a makefile problem. The issue did not exist before your changes. IMHO, this repo needs to revert back to the Dec 5 build as these changes just break things and hold no value at all.

**Comment by lavanoid** [comment]
@urherenow You're from Japan!? :O Happy new year!

**Comment by 173210** [comment]
@urherenow Let me explain what occurs.
Makefile gives the arguments, which is proper, at least in Unix. My `ImageMagick` is using Cygwin, so it can interpret the arguments, but your `ImageMagick` doesn't have. That's the problem.
Don't say something stupid such as "We should not use Cygwin or MSYS". In fact, your `make` is of MSYS. The inconsistency is what we are facing.

Anyway, I agree with you to revert f5096d5ddead1978ca6713087eb6100f524f964f. For you and many Windows users, it just breaks the build.

AND HAPPY NEW YEAR!!!!!!

**Comment by mariogamer2** [comment]
@173210 Don't know if it is the same issues for me (I'm on Ubuntu 15.10)

**Comment by AlbertoSONIC** [comment]
*trying to fix my hangover xD*

@173210 If you think you can't fix this on windows, then we have to revert...

**Comment by 173210** [comment]
@mariogamer2 Please tell me the detail.
By the way, my environment is:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Xenial Xerus (development branch)
Release:	16.04
Codename:	xenial
```

**Comment by mariogamer2** [comment]
http://pastebin.com/4baqRLed

This is the log.

**Comment by 173210** [comment]
@mariogamer2 I guess not. Did you update devkitARM? CakeHax seems broken.

**Comment by urherenow** [comment]
You updated your devkitARM. You must add the memset function to Cakehax/make.c or revert ctrulib to 0.6.0.

**Comment by mariogamer2** [comment]
It's not working with ctrulib 0.6.0

**Pull request merged**
