### PR TITLE
Unicode support

### PR DESCRIPTION
**Pull request by dukesrg**
Using GNU UniFont as a font source
Added widechar/Unicode support
Moved language-specific constants to separate header
Warnings fixed
Added unicode button characters for A/B/X/Y
Added russian translation

Limitation and bugs:
Only first 0x600 glyphs because of file size limitation (need to move font data outside) i.e. no CJK yet
A/B/X/Y button glyphs are trashed because of the above
Fixed to theme '0' because of the theme number bug appeared after switching to unicode
Several submenus with console/text output do not work/hangs
Strange va_list behaviour with %s\%S formats

upd: strange format behaviour because I was referred to MSDN format string specification instead of C99, fixing it now...

upd2: fixed all, added build-in ASCII 7-bit + external full unicode font support. Need to test this version before merging

upd3: menus and font load working fine, fixing small glitches with semi-proportional font symbols

### CODE REVIEW

**Comment by dukesrg** [comment]
Now can be merged, fully functional with several glitches:
- escape character appeared at first position of menu console for special files dump, after that it persists in settings menu and other console menu options
- second part of nand dump progress bar have a changed character (by -1) while source have all the same

**Comment by Syphurith** [comment]
@dukesrg So this clears the way to external language supports, and more customizable theme.
If that already good enough, you could change the title, just the `Edit` button around the pull name.

**Comment by dukesrg** [comment]
@Syphurith Thanks, I thought I already did it yeterday :) Anyway @AlbertoSONIC  is PMed about that :)
I believe @173210 will add JSON support soon so we can move all language definitions outside

**Comment by 173210** [comment]
JSON implementation is already completed. I'm waiting for #63 ...

**Comment by dukesrg** [comment]
@173210 I hope UniFont GPLv2+ wont' interfere?

**Comment by 173210** [comment]
@dukesrg It's completely OK.

**Pull request merged**
