### PR TITLE
Revert "Translation for all features" until it's fully functional

### PR DESCRIPTION
**Pull request by AlbertoSONIC**

### CODE REVIEW

**Comment by dukesrg** [comment]
@AlbertoSONIC I've finished translation changes but now just cant PR , because of your rever. I'm actually don't know how to rebase with my changes now!

**Comment by AlbertoSONIC** [comment]
Mmmm this is a problem

**Comment by AlbertoSONIC** [comment]
Can't you manually reapply changes? I mean, copy the rxtools folder to somewhere else, sync and do another PR with changes

**Comment by dukesrg** [comment]
Done! #131

**Comment by AlbertoSONIC** [comment]
I can merge it?

**Comment by dukesrg** [comment]
NO! json is still faulty parsing.

**Comment by AlbertoSONIC** [comment]
Ah ok! :D

**Comment by dukesrg** [comment]
@AlbertoSONIC will try to find a solution next week. Since I don't have clue what's wrong with it right now. Maybe overloading with several consecutive json files could work as a temporary workaround if there is only json parser issue.
Anyway, you can check this commit by yourself, booting should work fine. As for menus it should only work with reduced trahslation file. I'll did not manage to fit all the needed translation strings into stable 63 even with moving some fixed strings and acronyms to lang.c.
As a bonus, this version is able to boot with no external font and/or any translation files.

**Comment by AlbertoSONIC** [comment]
Oh nice! Take your time ;)

**Pull request merged**
