### PR TITLE
rxmode/native_firm

### PR DESCRIPTION
**Pull request by 173210**

### CODE REVIEW

**Comment by nastys** [comment]
@AlbertoSONIC Why not Sysn/Emun, or Ver+/RX-E, or even RSYS/REMU?

**Comment by AlbertoSONIC** [comment]
RX3D and Ver+?

**Comment by 173210** [comment]
So that can distinguish rxMode with normal mode?

**Comment by AlbertoSONIC** [comment]
Yes

**Comment by 173210** [comment]
In my humble opinion, the current behavior that rxTools boot sysNAND when emuNAND fails may be a far more serious problem.
Users may say the display is bad, but they may have tried to boot emuNAND which is not installed and jumped to sysNAND :P

**Comment by AlbertoSONIC** [comment]
It boots sysnamd but also sets the label to "Ver." which is enough for the user to know that the emunand hasn't been booted.

**Comment by 173210** [comment]
But if I were a noob, I would want to tell me when it fails to boot emuNAND.

**Comment by AlbertoSONIC** [comment]
ConsoleInit();
ConsoleSetTitle("EMUNAND NOT FOUND");
print(L"The emunand was not found on \n");
print(L"the sdcard. \n");
print(L"Press A to boot the sysnand \n");
ConsoleShow();

**Comment by 173210** [comment]
@dukesrg It's not a good idea to do several things in a commit. And don't worry, I just pushed 25 commits a day.
But, actually we may have too many merging commits. Using git --rebase or giving me a writing permission is the easy solutions.

**Pull request merged**
