### PR TITLE
Theme generation moved to makefile

### PR DESCRIPTION
**Pull request by dukesrg**

### CODE REVIEW

**Comment by Syphurith** [comment]
Eh.. Why that is rotate 90? Sorry i don't know what exactly we are trying to do with those pictures. @AlbertoSONIC If please tell me about it? I would think of using nodejs scripts to do so if possible.

**Comment by nastys** [comment]
@dukesrg Adding theme generation to makefile is a good idea, but the scripts should not have been removed, because they are still useful for custom theme creators and testing. I'm going to improve the scripts and put them into a separate folder.

**Comment by dukesrg** [comment]
@nastys There was only one actual convert call per file in the old scripts, I had no idea how they could be used for anything else. You can always run 'make theme' or 'cd theme; make' to just convert theme files

**Comment by nastys** [comment]
@dukesrg Yes, but I assume theme creators don't have or don't know how to use "make" and also there will be a lot more scripts.

**Comment by dukesrg** [comment]
@nastys For theme creators it is better to make a separate repo with all tools.

**Comment by nastys** [comment]
@dukesrg My goal is to make theme creation as simple as possible. Maybe an all-in-one script would be a good compromise.

**Pull request merged**
