### PR TITLE
Update CakeBrah

### PR DESCRIPTION
**Pull request by mariogamer2**

### CODE REVIEW

**Comment by Shadow322** [comment]
This Fix black freeze issue with ninjhax 2.x?

**Comment by mariogamer2** [comment]
Please tell me if I done an error in language file and also if I have to remove other things.

@Shadow322 Yes

**Comment by Shadow322** [comment]
@mariogamer2 can I get a compiled copy please?

**Comment by urherenow** [comment]
I uploaded a compiled copy days ago. Github is for issues and solutions, not to be a help forum.

**Comment by Shadow322** [comment]
@urherenow link please

**Comment by urherenow** [comment]
https://gbatemp.net/threads/release-rxtools-roxas75-3ds-toolkit-fw-2-0-9-2.382782/page-926#post-6141931 For the updated cakebrah. The full build is a couple of pages back.

**Comment by mariogamer2** [comment]
@AlbertoSONIC Can I revert a part of #443 ? ( https://github.com/roxas75/rxTools/pull/443#commitcomment-16378790 )

**Comment by mariogamer2** [comment]
@dukesrg Already implement this,and I'll delete...

**Pull request closed without merging**
