### PR TITLE
Use $(MAKE) instead of make in Makefiles

### PR DESCRIPTION
**Pull request by 173210**
$(MAKE) has many advantages to just calling make.
See this page for the detail.
https://www.gnu.org/software/make/manual/html_node/MAKE-Variable.html#MAKE-Variable

### CODE REVIEW

**Comment by Syphurith** [comment]
Would wait to see if anyone faces problems with `$(MAKE)`. Iirc it was changed some commits ago.

**Comment by 173210** [comment]
Yes, I'm facing the problem. I'm aiming to use job option to make build faster to provide nightly builds.

**Comment by dukesrg** [comment]
Last time I was changing $(MAKE) with make was when sources path haveva space sign. Not a big deal but newbies will be yelling about not compiling. And I don't know how to escape spaces in makefile

**Comment by 173210** [comment]
```
make[1]: Entering directory `/c/Users/root3/Documents/GitHub/rx Tools/rxtools'
make[2]: /c/Users/root3/Documents/GitHub/rx: No such file or directory
```
Actually it outputs errors.

**Comment by Syphurith** [comment]
@dukesrg Try quote them with `"`. As in windows, many programs recognize it.

**Comment by 173210** [comment]
@Syphurith Exactly it's the usual way to escape spaces. However, we can't do that for $(MAKE) because $(MAKE) includes both of the command and options.
So we must evaluate which is more important, options or space escaping. I don't prefer to use bare `make` because it's not recommended by GNU.

**Comment by Syphurith** [comment]
@173210 or simply tell users there should be no space when building it. Or fix it themselves?

**Comment by 173210** [comment]
Yes, I think it's the best way to tell users so.

**Comment by dukesrg** [comment]
So we need to update Readme.md to incidate source path restriction. Because I've already troubleshooted at least one with spaces!

**Comment by 173210** [comment]
I close this pull request for now.

**Pull request closed without merging**
