### PR TITLE
Remove .pdf docs until they are updated and include README.md in release

### PR DESCRIPTION
**Pull request by urherenow**
Takes care of #346

### CODE REVIEW

**Comment by urherenow** [comment]
@AlbertoSONIC this and #344 are safe to merge. #351 I think should be ignored.

**Comment by AlbertoSONIC** [comment]
I'll leave @nastys to do this ;)

**Comment by urherenow** [comment]
I'm not deleting them. This change simply leaves them out of the release folder for now and adds the readme.md, which is sorely needed since it has the correct browser link.

**Comment by urherenow** [comment]
@AlbertoSONIC I don't understand why you don't merge this. Why not include the README.md in the release, and why include docs with incorrect information. Those docs do not apply to current builds at all. Again, this commit isn't getting rid of those docs; it's just leaving them out of the release folder until they are updated.

**Comment by AlbertoSONIC** [comment]
@urherenow Because I'm not the only member of the Pasta Team and since it was @nastys to work on docs, I'll just leave him this PR. Just because this PR has to do with docs!

**Comment by nastys** [comment]
I'm sorry, I've only just noticed this PR...

**Pull request merged**
