### PR TITLE
More information about the N3DS keys.

### PR DESCRIPTION
**Pull request by Mrrraou**
The instructions about the N3DS keys were confusing.

### CODE REVIEW

**Comment by Ninoh-FOX** [comment]
confusing not impossible, I tried to remove the keys from reinand code but have not been able, if they refuse to publish the keys to remove them unless they say as the NAND New3DS least dammit !!

**Comment by Ninoh-FOX** [comment]
confusing not impossible, I tried to remove the keys from reinand code but have not been able, if they refuse to publish the keys to remove them unless they say as the NAND New3DS least dammit !!

**Comment by Mrrraou** [comment]
Search for "N3DS arm9bin decryption keyX 9.6" (a pastebin, called "Some relevant N3DS keys") => it is key_0x16.bin
and for a pastebin called "New 3DS 0x1B 9.6.0-X NCCH key" => it is key_0x1B.bin

**Comment by Ninoh-FOX** [comment]
Thanks XD

**Pull request merged**
