### PR TITLE
Update firmware loader and fix FileExplorerSelect

### LINKED ISSUE #137: New elf patches are not working with 9.x emuNAND on 4.x sysNAND consoles (JAP/TWN/CHN tested)
Tried many times but still got black screen and it works when I revert rxTools to an old version before new patches codes.
My console is TWN 4.4.0 and emuNAND is 9.9.0 JPN (Region converted by import SecureInfo_A from a Japan console).

### PR DESCRIPTION
**Pull request by 173210**
Commit 480ecd946be8b58cb4ca1f964f0d9ec788febfac fixes #137.

### CODE REVIEW

**Comment by soarqin** [comment]
Tested this, 9.9.0 emuNANDs of JAP/TWN consoles are still not working.

**Comment by 173210** [comment]
@soarqin It works with 4.5.0-10J sysNAND and 9.9.0-26J emuNAND.

**Comment by soarqin** [comment]
@173210 I have already used codes in your repo to test on my JAP console

**Comment by 173210** [comment]
@soarqin So you updated code.bin and native_firm.elf?

**Comment by soarqin** [comment]
@173210 not sure, I am trying to recompile codes in main repo for recheck

**Comment by soarqin** [comment]
@173210 Tested latest codes and everything works, I think I missed your last commit in previous test, it is puhsed 2 hours ago to this PR, which is later than my previous test, it's my fault.

**Pull request merged**
