### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by 173210**
See also #280. Now it works even with the broken shell.
As I said in #280, it needs to be tested with extended RAM games, especially on old 3DS.

### CODE REVIEW

**Comment by Matsumot0** [comment]
so i repost my feedback here, i can't test a game like SSB cause my homemenu crash after few seconds when my sysnand/emunand is loaded with this build.

O3DS 9.2 launch via downgraded mset 6.X

**Comment by 173210** [comment]
@Matsumot0 It works on my old 3DS (from sysNAND 4.5 to emuNAND 10.1), launched via MSET. Can you test another firmware?

**Comment by 173210** [comment]
Tested on:
RX-S 4.5, RX-E 10.1, RX-E 10.2

**Comment by Matsumot0** [comment]
i don't have any backup of emunand on 10.1 :(

**Comment by 173210** [comment]
@Matsumot0 I updated my emuNAND to 10.2 and it works. Please use 10.2.

**Comment by Matsumot0** [comment]
i'm on 10.2 that's why it's so fckin weird Oo

**Comment by 173210** [comment]
@Matsumot0 I had the same symptom when I modified @AlbertoSONIC 's k11_codeset hook. So something of ARM11 goes wrong on your 3DS.

Does anyone else have the same problem?

**Comment by kot2002** [comment]
String on rxTools menu got weird. It's splitted.
And after booting, screen gets black and white with stripe and crashes.

**Comment by 173210** [comment]
@kot2002 I didn't modify the UI at all. The screen flashing is similar to DEBUG_DUMP_FCRAM, but it's not enabled, as you can see.
https://github.com/173210/rxTools/blob/master/rxmode/native_firm/source/payload/arm9/myThread/myThread.c

**Comment by kot2002** [comment]
Well, you can check UI out before this commit and this one.
And sadly I don't have much knowledge on that, so all I can say is whether it works or not.

**Comment by Matsumot0** [comment]
exactly the same symptom black and white with stripe and crashe, but no 
issue in my rxTools menu

**Comment by 173210** [comment]
@kot2002 It works fine on my 3DSes. I mean it works even without using the old code.

I have no idea why it doesn't work. I'll try to build the source code on Windows.

**Comment by kot2002** [comment]
Could you please upload your build on your repo? So I can test out.

**Comment by 173210** [comment]
LOL The binary built on Windows doesn't boot. But it's likely my fault because others can boot.
@kot2002 Sorry, but I can't due to the law. (even some has been arrested.)

**Comment by kot2002** [comment]
Oh.. Your country's law is discouraging.. I will test out after you figuring out the fix.

**Comment by 173210** [comment]
The binary I built again booted and had the white screen. So this should be a fault of the broken Windows.

**Comment by Matsumot0** [comment]
Oh that's why i saw a long text of law in front on your blog about github & rxtools :-)
Anyway so it's windows again :-1:  damn OS ^^'

**Comment by 173210** [comment]
The problem is in rxTools/sys/code.bin.

**Comment by kot2002** [comment]
Ubuntu 14.04 : Fail with latest devkitarm and ctrulib

**Comment by urherenow** [comment]
As I posted on the main rxtools tree, I built the latest tree from here and on N3ds, is tries to boot emunand (even if I manually pick SYSNAND from the menu) but never quite finishes loading. It shows the theme (which is how I know it's emunand) and only a few of the home menu icons. I can move around the screen until I try to launch something but then it freezes (with bgm still going).

**Comment by 173210** [comment]
I found that it depends on the condition of the file system whether the white screen of death occurs. It's quite a difficult to know the cause.

**Comment by urherenow** [comment]
If it helps, my issues got even worse when I added the /firm folder and threw the appropriate _cetk in it (at that point, ctrbootmanager would immediately freeze when selecting rxtools).

**Comment by AlbertoSONIC** [comment]
@urherenow It's completely unrelated. Also, I also get a freeze on ctrbootmanager almost everytime I try to boot rxTools!

**Comment by 173210** [comment]
Everything can be related to the crash. I suppose it's interruptions and collecting evidence...

**Comment by urherenow** [comment]
@AlbertoSONIC have you updated everything to the latest? I can boot fairly consistently (although not 100%) to either sysnand or emunand through ctrbootmanager b08, launched with menuhax 2.0. That's with the current roxas75 tree, not 173210's.

**Comment by Matsumot0** [comment]
@173210 After few tests, i can confirm the crash issue "black & white with stripes" is coming since this commit 938bdec, my o3ds do not crash again with the previous commit 6ccf3ad

**Comment by AlbertoSONIC** [comment]
@173210 not a missing cetk file

**Comment by 173210** [comment]
Identified: The issue is interruption. I'll make a patch.

**Comment by Matsumot0** [comment]
nice :+1:

**Comment by 173210** [comment]
Ok, the issue should be fixed with commit 41739e9dea12423bf93563e4dede733bb4f372a8. Please check it out.

**Comment by urherenow** [comment]
@AlbertoSONIC I think you misunderstood about the cetk file. I just added it for troubleshooting (to see if maybe the code was hanging on a procedure... I know, it's kind of pointless without a debugger...) and adding it actually made the situation worse than it was. So believe it or not, having it does have an effect.

**Comment by Matsumot0** [comment]
@173210 nop still crashing :(

**Comment by 173210** [comment]
@Matsumot0 Hmm, it's really strange. I also had a look at a different implementation (i.e. CakesFW), but they are completely same.

**Comment by AlbertoSONIC** [comment]
@urherenow Having or not having the cetk file has an effect on rxTools, not on ctrBootManager!

**Comment by kot2002** [comment]
Well, I still have the same issue. Both ubuntu-build and windows-build are crashing.

**Comment by urherenow** [comment]
@AlbertoSONIC I'm aware of that! That was my whole point. Without the /firm folder and cetk in there, I could boot into the rxtools menu. EIther autobooting emunand or manually selecting sysnand would still cause it to partially boot into emunand. Adding the folder and cetk caused it to not even go that far. It identifies yet another problem with the way these things are being coded. There aren't enough checks, balances, and returns (or skip over) if a procedure doesn't apply. If the N3DS doesn't need the cetk, then it shouldn't even be checking for one, let alone do anything with it and halt progress.

On a lighter note, it's the same deal with the new cdn_firm.py. Try running it twice from the command line. Downloading 3DS firmware from the CDN and you get:

Traceback (most recent call last):
  File "cdn_firm.py", line 14, in <module>
    os.mkdir(firmdir)
WindowsError: [Error 183] Cannot create a file when that file already exists: 'firm'

because it doesn't check if it exists or not. Why would someone need to run it twice? In my case, my stupid ISP specifically blocks the 00000049 file (which I always forget about) and I have to paste the link to it in my browser where I get a button from my ISP to let me download it anyway. Granted, it's not the usual case; just an example of why there needs to be checks and balances.

**Comment by Syphurith** [comment]
@urherenow See if #285 edits fixes this little issue of your `cdn_firm.py`.

**Comment by 173210** [comment]
I read the reference manual and found it has "write buffer", different from data cache. 34d48e3e97a96281db1fff5ce621ceb469e9bb12 is a fix for that.

**Comment by 173210** [comment]
Now this should work. Please try again.

**Comment by Matsumot0** [comment]
with 34d48e3? i've already tested yesterday it's still crash on my home menu :s

**Comment by 173210** [comment]
I want to make sure that the booting process works to concentrate on other bugs.

**Comment by Matsumot0** [comment]
yes i've still the white screen on the bot screen

**Comment by 173210** [comment]
Wait, I had white screen on the top screen, and it was before showing the home menu.
Did you have a different bug...?

**Comment by Matsumot0** [comment]
on the top i had black screen with stipes, for you it's was before showing the home menu oO
For the crash it's happened after the home menu load

**Comment by 173210** [comment]
@Matsumot0 Yes, it's enough to understand the difference. Well, if the issue is in the booting process, the cause is clear, but it's actually not. I suppose the new reboothax overwrote something necessary for your background process (maybe StreetPass or something kind of that?) I'll make a test branch which ignores the patch of reboothax.

**Comment by 173210** [comment]
I made branch "test". Please tell me whether it works.
https://github.com/173210/rxTools/commits/test
The test commit is e27b5214b8d45753fddd3a072d2ac5a7163fb6ff.

**Comment by Matsumot0** [comment]
Same thing on my emunand crash black stripes top & white bot even without patch of reboothax :(

**Comment by m45t3r** [comment]
Can confirm the same issue: black/white stripes in Home Menu after booting in emuNAND. Tested both with and without commit e27b521.

**Comment by kot2002** [comment]
All I can see is this glitch after I see icons about 1 sec. http://i.imgur.com/SxJS71I.jpg

**Comment by 173210** [comment]
The strange fact is that both of my new and old 3DSes don't have the symptom while all others do. I think the significant difference is that I don't do games with my 3DSes.

**Comment by kot2002** [comment]
Well, a strange error: 
I got into sysnand mode. It didn't freeze or crash but after I moved cursor to other apps like settings, it froze.

**Comment by 173210** [comment]
@kot2002 It's an ARM9 error, as far as I know.

**Comment by AlbertoSONIC** [comment]
Some time ago I tried to dump the fcram using the arm9 mythread... Before @173210 fopen9/fread9/fclose9 fix. Once I pressed the Select button (which should start the dump), the background music disappeared and once I moved the cursor, the 3DS completely freezed... This is very similar (if not identical) to what @kot2002 is experiencin!

**Comment by 173210** [comment]
Can anyone provide a binary which has the issue for comparison?

**Comment by Syphurith** [comment]
@173210 Eh they might be inactive now. Why don't you ask them for an ELF, that contains signatures?

**Comment by 173210** [comment]
I pushed commit f3e427a72b090a409ba324fdac4880f75d8502d6 to test branch, bug I'm not sure whether it makes difference.

**Comment by Syphurith** [comment]
@173210 Not hard if you have bindiff and idapro to compile what is different. *asking for a pirate*

**Comment by 173210** [comment]
@Syphurith arm-none-eabi-objdump is enough for me. ;)

**Comment by Syphurith** [comment]
@173210 Oh yeah you expert have surely more ways than me!

**Comment by Matsumot0** [comment]
* On test branch, i've got a freeze when a move my cursor on a game.
* On master branch, same thing black stripes top but my bot screen is black now instead white.

@173210 if you want something tell me your :e-mail: i'll send you my binaries.

**Comment by 173210** [comment]
@Matsumot0 Thank you.
https://github.com/173210/capusbpsp/blob/master/main.c#L2

**Comment by Matsumot0** [comment]
Euh excuse me? lol

**Comment by 173210** [comment]
@Matsumot0 The binary which doesn't work.

**Comment by Matsumot0** [comment]
oh lord k you show me your mail lol, sorry i just wake up... 6am -_-'

**Comment by 173210** [comment]
LOL @Matsumot0's binary works on my 3DS :/

**Comment by b-** [comment]
BUT WHAT DOES IT MEAN???

**Comment by Matsumot0** [comment]
@173210 You kidding right?? XD

**Comment by 173210** [comment]
@b- It depends on *something* in my 3DS (data in NAND?)

**Comment by 173210** [comment]
@Matsumot0 master.

**Comment by Matsumot0** [comment]
rxTools don't like 9.X fw lol, someone on 4.5 can maybe also test it?

**Comment by 173210** [comment]
@Matsumot0 My 3DSes, which rxTools works fine:
old: RX-S 4.5, RX-E 10.2
new: RX-S 9.2, RX-E 9.2

**Comment by Matsumot0** [comment]
i don't understand, i always cleaning my rxTools installation everytime i compile another one, and my o3ds 9.2 is clean i just downgraded my mset to 6.X? that's all.

Like i said it's the first a saw a freeze/crash like this :O

**Comment by 173210** [comment]
Added commit aab44c565035116b24e1e92eb3f4b6927b3ad4f2 to test branch.
This removes all patches. Please test it.

**Comment by Matsumot0** [comment]
Ok so without any patch my o3ds doesn't freeze anymore on my sysnand.

**Comment by 173210** [comment]
@Matsumot0 So the signature hack has a fault?

**Comment by Matsumot0** [comment]
indeed it's possible

**Comment by 173210** [comment]
LOL FBI is working on my 3DS :/

**Comment by 173210** [comment]
I made another test commit to leave some patches alive (79001a3d8caeb7153965eb78254a021e1bf1d853).
Please test again.

**Comment by Matsumot0** [comment]
i saw, i'll testing right now.
RSS feeder :heart: is aware :p

**Comment by 173210** [comment]
I'm trying to figure out which patch has the issue. Some patches depend on others. See the below.
```
EmuNAND.o -> ctx.o
myThread.o -> CreateThread.o -> process9.o, ctx.o
p9_mythread_hook_1.o <-> p9_mythread_hook_2.o
p9_reboothax_entry.o <-> p9_reboothax_body.o
```
I'll go to bed, so please try to figure out the issue by removing patches by yourself.

**Comment by Matsumot0** [comment]
.patch.p9.reboot.body not found :sa: 

ok, i'll try to do something.

**Comment by 173210** [comment]
@Matsumot0 Sorry, I forgot to enable p9_reboothax_body.o. Good luck. ;)

**Comment by Matsumot0** [comment]
Ok thanks, have a good night :+1:

**Comment by Matsumot0** [comment]
@173210 Ok after some tests, you're right the issue is the signatures spoof if i disable only this patch my o3ds works well, IMO this patch comes into conflict with other module or patch, i don't think the problem is inside the patch itself.

i've not much knowledge like you, especially on nintendo 3ds...
I hope you can find the problem soon, it's really difficult to a dev when everything works fine on his device, i know what i talking about.

**Comment by 173210** [comment]
@Matsumot0 I made commit c9b635eb145263019d4a99cb294be58fa2ce2e34. This is the first attempt to fix the patch.
https://github.com/173210/rxTools/commit/c9b635eb145263019d4a99cb294be58fa2ce2e34

Thank you!

**Comment by kot2002** [comment]
source/p9_signatures_spoof_2.S: Assembler messages:
source/p9_signatures_spoof_2.S:22: Error: lo register required -- `ldr pc,=0x806
3866'

**Comment by 173210** [comment]
@kot2002 Fixed (4a9d9652ac870b3a722622eacfd939a5e5856be8)

**Comment by Matsumot0** [comment]
yep i'm back, i going to test it right now :)

**Comment by kot2002** [comment]
4a9d9652ac870b3a722622eacfd939a5e5856be8
freezes after loading few icons.

**Comment by 173210** [comment]
Added d0cfef42a2d08dbde8072a7da8639c1bea1ea2e2 to test branch. Please tell me whether it works.

**Comment by Matsumot0** [comment]
Still freeze when a move the cursor on any game :(

**Comment by 173210** [comment]
I found an issue in the thumb code alignment. 5641d41a1f087345b2fad587e714701fbe8b0744 is a fix for that. I also rebased to the latest revision of https://github.com/roxas75/rxTools/ (ed417d099653a7e6b0a3f4b0866751152421cc6e) .
Please tell me whether it fixes the screen stripe bug.

**Comment by kot2002** [comment]
5641d41a1f087345b2fad587e714701fbe8b0744 
Oh, it is working! Great job.

**Comment by Matsumot0** [comment]
Yes it's working!
No more freeze, black & white screen with stripes :+1:

Now like @kot2002 said games that uses extended RAM are not working.

**Comment by 173210** [comment]
So there is another bug which I can't reproduce: the boot failure of extended RAM games.
Is there a free alternative of such games (except piracy)?

**Comment by Syphurith** [comment]
@173210 I'm afraid not, unless smash demo uses the extended ram. This was happened before, in #163. The list is short; i doubt if that is acceptable for you to let someone else (for example @soarqin) use your special build and test the patches for you. ~~*Unfortunately i do not play any of those..*~~

**Comment by shadowofdarkness** [comment]
@173210 I'm not sure if it would be region locked but if not would a demo code for Monster Hunter 4 from NA work for you. I think I have one unused. I know it uses extended ram since I just tested it and the browser wouldn't open and it rebooted the system when closing it.

Plus the demo code is for unlimited uses for extended testing without running out at 30 tries.

**Comment by Matsumot0** [comment]
Yep this code without running out 30 tries seem to be the only free solution except piracy.
I hope it's works on a JP Eshop region.

**Comment by Syphurith** [comment]
@shadowofdarkness That's quite a special demo. Thank you for ever offering him that.

**Comment by shadowofdarkness** [comment]
I'll PM the code on gbatemp so no one can snipe it if posted publicly. I'm 95% sure it is unused so I hope it's not the other 5.

**Comment by 173210** [comment]
Please test 5de251dc8c6952ace7029b334e66a49a6b6a5303.

**Comment by kot2002** [comment]
5de251dc8c6952ace7029b334e66a49a6b6a5303
MH4U and SSB are not working on this build.

**Comment by 173210** [comment]
I made test branch again. Commit c29e00e1747be86fee65e29f6d577dfd74c7e0db clears the screen with grey or white. Please tell me the result.

**Comment by kot2002** [comment]
What you expect with c29e00e1747be86fee65e29f6d577dfd74c7e0db is screen flickering when I run those games, right?
Well.. I don't see any gray or white screen. Just nintendo 3ds splash and then black screen.

**Comment by Matsumot0** [comment]
yep same thing here.

**Comment by 173210** [comment]
06de65723e172ee98e005d101e8ef86eb55fd655 makes files instead of clearing VRAM.
Please tell me what it makes at the root directory of SDMC.

**Comment by Matsumot0** [comment]
It makes A & B

**Comment by 173210** [comment]
I made a fix (bb18b0cc8fcb2fea3d9b13c5075423115d1e998e).
Please tell me whether it makes difference.

**Comment by Matsumot0** [comment]
i saw, nop same thing

**Comment by 173210** [comment]
53b22cdd3f97ae4cf9e2a70e3a19725aa039293c is to know which causes the error, p9RecvPxi or svcKernelSetState.

**Comment by Matsumot0** [comment]
k now it's C only

**Comment by 173210** [comment]
bc5999290e7333fac25052e2d53c03cbe44177a5 changes arguments for svcKernelSetState.
Now it should be able to create `sdmc:/d`.

**Comment by Matsumot0** [comment]
nop still C only

**Comment by 173210** [comment]
Removed debugging code (5fa76d76ad1dbe296434b0bcd9ec92079eb2e10c). Does this work?

**Comment by kot2002** [comment]
53b22cdd3f97ae4cf9e2a70e3a19725aa039293c
Working. MH4U and SSB.

**Comment by Matsumot0** [comment]
Yes i confirm also it's working :+1: 
@173210 great works :)

**Comment by 173210** [comment]
I added commit 99c5eeca42c67503346e8116e6a37981b5cb4ded. This must be checked before applying changes in master branch.

**Comment by 173210** [comment]
If the revision works, please review master branch and merge.

**Comment by kot2002** [comment]
Both test and master branch are working nicely. Good job.

**Comment by Matsumot0** [comment]
Yep everything works fine also in testing/master branch with lasted merge! :)

**Comment by AlbertoSONIC** [comment]
@173210 Thanks for everything! Can I tap the merge button? :)

**Comment by 173210** [comment]
@AlbertoSONIC Yes. Sorry for bothering with bugs.

**Comment by AlbertoSONIC** [comment]
No problems :D

**Comment by Matsumot0** [comment]
Great job soldier :+1:

**Comment by kot2002** [comment]
I am sorry to bother you guys.. AGB FIRM patch is broken.. :( ..

**Comment by AlbertoSONIC** [comment]
:-1:

**Comment by Matsumot0** [comment]
arf i didn't have test gba games i've no one of them :(

**Comment by 173210** [comment]
Does TWL work?

**Comment by kot2002** [comment]
TWL does not working either..

**Comment by 173210** [comment]
Can anyone try AGB or TWL with 5fa76d76ad1dbe296434b0bcd9ec92079eb2e10c?

**Comment by kot2002** [comment]
5fa76d76ad1dbe296434b0bcd9ec92079eb2e10c
Both are not working.

**Comment by 173210** [comment]
Well, so, the problem is that I can't reproduce the issue :/
img_20151107_223429622
/* This is 1BitBallWall, a homebrew with nice sounds. :) */

**Comment by Matsumot0** [comment]
arf :(
Can you share it with us the file?
I wanna test this gba homebrew under cia format.

**Comment by 173210** [comment]
I succeeded in crashing LOL Now I'm fixing bugs.
An issue opened by @kot2002 (#290)

**Pull request merged**
