### PR TITLE
Revert "Output files in the same directory"

### PR DESCRIPTION
**Pull request by 173210**
This reverts commit f5096d5ddead1978ca6713087eb6100f524f964f.

\# Conflicts:
\#	Makefile
\#	rxtools/Makefile

See also #322.

### CODE REVIEW

**Comment by Shadow322** [comment]
This will compile correcly under what was needed for 12-5 build r44 and the ctrlib?

**Comment by lavanoid** [comment]
Why not test and find out for yourself :)

**Comment by mariogamer2** [comment]
I'll test with ctrulib 0.6.0/1.0.0

**Comment by urherenow** [comment]
I dorked up my devkitArm bouncing between versions. I just deleted the whole devkitPro folder and installed the latest from scratch (with the ctrulib 1.0). With the latest cakehax and cakebrah, this builds perfectly and is pretty damn stable, if you ask me.

**Comment by mariogamer2** [comment]
All run fine using:

DevkitARM r45
ctrulib 1.0.0
Cloning CakeHax/CakeBrah/CakesROP by myself

This is good!!! @lavanoid You can upload it to your website.
I'll test now.

**Comment by lavanoid** [comment]
Will upload when the bot gets put back online.

**Pull request merged**
