### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by 173210**
Same as #278, but excluding a79676a5a502811804e013861a912c19efb71945.

### CODE REVIEW

**Comment by 173210** [comment]
Added commit 5d7874ad7fb651c6c1c8fe27364691128b752e2f.

**Comment by 173210** [comment]
Added commit 8594bc4c4e4e3d12e42c56d841794049def1f2b8.
This solves the radical problem of installation.
Please confirm that extended RAM games work both on old 3DS and on new one.

**Comment by 173210** [comment]
Added commit fb6a78e24f63de3de62b6a324f069b2463f7ad9c.
This solves the radical problem of installation.
Please confirm that extended RAM games work both on old 3DS and on new one.

**Comment by 173210** [comment]
Added commit 2461a8a7ca084aee7c163eac2b77f40b1b6e082c.
This solves issue #281.

**Comment by AlbertoSONIC** [comment]
Afaik reboot hax is not used on n3ds with extended ram games, as n3ds has the extended ram.

**Comment by 173210** [comment]
@AlbertoSONIC So the rebooting code is only to boot AGB and TWL? Anyway, please check on old one.  This also changes old 3DS code.

**Comment by AlbertoSONIC** [comment]
@173210 Yeah on n3ds is only for twl and agb firm boot. Also I can't try extended ram games on my o3ds as I don't have any game...

**Comment by 173210** [comment]
Commit 5c9d55434060da4fb639b3628d8147351da43e69 solves issue #276.

**Comment by 173210** [comment]
Commit e47b503673072467a7ac57f198d45db1a05516ad solves issue #274.

**Comment by kot2002** [comment]
Reverting CakeBrah will cause ninjhax2(menuhax, browserhax, etc) incompatibility.

**Comment by Matsumot0** [comment]
@173210 Feedback: I've tested your last git push, o3ds 9.2 with themehax/bootctr hax 2.5 31/10
- On the emunand, i've got a crash on my home menu after few seconds :s

**Comment by urherenow** [comment]
Are your NANDs linked? Using themehax like that can cause issues. And how exactly do you grab a push request that hasn't been committed yet, using command line git? Or did you manually make the updates on your end?

**Comment by Matsumot0** [comment]
i've git pull on his fork of course, my emunand are unlinked and i'm pretty sure themehax isn't the problem of this crash but i can test like as before mset ds profil if you want ;)

**Comment by urherenow** [comment]
Pate the command here please?

**Comment by kot2002** [comment]
Compiling error:

make[2]: *** No rule to make target `/c/rxTools/rxmode/build/
ktr/payload/arm9', needed by `/c/rxTools/rxmode/build/ktr/pay
load/arm9/EmuNAND.o'.  Stop.
make[1]: *** [build/ktr/native_firm.elf] Error 2
make: *** [rxmode/build/ktr/native_firm.elf] Error 2

**Comment by Matsumot0** [comment]
@urherenow this fork, git clone --recursive https://github.com/173210/rxTools.git

**Comment by kot2002** [comment]
The same fork you mentioned.

**Comment by Matsumot0** [comment]
that's wieird i don't have this issue :s
i just tried to compile it right now, no issue at all

**Comment by urherenow** [comment]
Tried that and got the same error as dean. I was thinking you were using the roxas75/rxtools and somehow merging the push request with the tree on your PC.

**Comment by 173210** [comment]
@kot2002 Your rxmode/native_firm/Makefile is outdated. The latest one do no longer require the target.
https://github.com/173210/rxTools/commit/362ab997cc9a7598ab54e8d771773faf4a048e70#diff-688a9456d2406a423df048962830360dL100

**Comment by 173210** [comment]
```
git clean -d -x -f
git checkout .
make release
```
Actually it worked for me.

**Comment by urherenow** [comment]
@173210 did you try to make clean first? I got the same error from a fresh clone of your fork.

**Comment by 173210** [comment]
@urherenow `git clean -d -x -f` removes everything except files tracked by Git.

**Comment by urherenow** [comment]
Humor me. From nothing, git clone --recursive https://github.com/173210/rxTools.git followed by make release throws the same error that kot2002 was talking about.

**Comment by urherenow** [comment]
Scratch that. Followed by make clean, then make release. That's what I did anyway...

**Comment by 173210** [comment]
I got it. Windows ignores '/'. Windows always disrupts me.

**Comment by 173210** [comment]
For now, I close this pull request.

**Comment by Matsumot0** [comment]
@urherenow Trust me or not i've type this command and everything works fine 'make release'... 
of course i've removed my older rxTools folder and about the OS isn't the problem i'm on windows too.

I don't know why your building environnement cause this issue.

**Comment by urherenow** [comment]
@Matsumot0... @173210 already said why. Not sure why you bothered to reply again. The answer is Windows...

**Comment by 173210** [comment]
Ok, I confirmed Windows (GNU make in MinGW) is wrong.

/* osx is a friend, he is a unix. What about Windows? */

**Comment by Matsumot0** [comment]
i'm on windows 10.....

**Comment by 173210** [comment]
@Matsumot0 But your build is on Cygwin, right?

**Comment by Matsumot0** [comment]
nop MinGW

**Comment by 173210** [comment]
Ok, so the problem occurs only on Windows shell (stupid cmd.exe).

**Comment by Matsumot0** [comment]
Yes it's possible :+1:
i haven't tested with this stupid console ^^

**Comment by 173210** [comment]
I opened a new pull request (#283) Please check it out.
And I recommend to throw the shell away.

**Comment by urherenow** [comment]
He corrected it already.

**Pull request closed without merging**
