### PR TITLE
ARM9 Exception Handler and JSON Support

### PR DESCRIPTION
**Pull request by 173210**
Solves issue #92.

### CODE REVIEW

**Comment by Syphurith** [comment]
@173210 Eh i suggest you change this pull request title as "JSON support, SWI", other than 'Impro..'.

**Comment by 173210** [comment]
@Syphurith Thank you for your review. Now it's fine.

**Comment by Syphurith** [comment]
Once this is done and tested, and waiting for merge, you could tag motezazer capito27 nastys or AlbertoSONIC to call for them. *Though a little confused/interested of how to get JSON working..* I hope there would be another one take a look (at least literally, :smile: ).

**Comment by 173210** [comment]
@AlbertoSONIC Really? It can break the entire rxTools. Anyway, I think it's one of the most serious issues that we have many duplicated codes. They can prevent from the further development like N3DS support.

**Comment by AlbertoSONIC** [comment]
Yeah rxtools's rxmode pathes are full of o3ds only offsets. Starting from reboot/firmlaunch code...

Duplicated codes?

**Comment by AlbertoSONIC** [comment]
Also, I PMes you on gbatemp ;)

**Comment by 173210** [comment]
e.g. SVC

**Pull request merged**
